[project]
name = "estimate-model-web"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.1.0,<0.2.0",
    "langchain-community>=0.0.20,<0.1.0",
    "langchain-core>=0.1.0,<0.2.0",
    "langchain-openai>=0.0.5,<0.1.0",
    "langchain-google-genai>=0.0.6,<0.1.0",
    "altair",
    "amadeus",
    "cryptography",
    "datasets",
    "flask",
    "flask-migrate",
    "fqdn",
    "func-timeout",
    "googlemaps",
    "gunicorn",
    "grpcio-status",
    "isoduration",
    "langfuse",
    "pip-chill",
    "psutil",
    "simpy",
    "translate",
    "uri-template",
    "webcolors",
    "flask-cors",
    "flask-sqlalchemy",
    "pymysql",
    "json5",
    "diskcache",
    "pyyaml",
    "openai",
    "python-dotenv",
    "tiktoken",
    "pandas",
    "tqdm",
]
