"""Initial migration, create tables

Revision ID: 69ec2e1a49bd
Revises: 
Create Date: 2025-11-12 01:17:29.690450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ec2e1a49bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_estimate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=2000), nullable=True),
    sa.Column('gpt_response', sa.Text(), nullable=True),
    sa.Column('gpt_overall_rating', sa.Integer(), nullable=True),
    sa.Column('gpt_route_rationality_rating', sa.Integer(), nullable=True),
    sa.Column('gpt_representativeness_rating', sa.Integer(), nullable=True),
    sa.Column('trip_response', sa.Text(), nullable=True),
    sa.Column('trip_overall_rating', sa.Integer(), nullable=True),
    sa.Column('trip_route_rationality_rating', sa.Integer(), nullable=True),
    sa.Column('trip_representativeness_rating', sa.Integer(), nullable=True),
    sa.Column('trip_currency_unit', sa.String(length=10), nullable=True),
    sa.Column('trip_transportation_cost', sa.Float(), nullable=True),
    sa.Column('trip_attractions_cost', sa.Float(), nullable=True),
    sa.Column('trip_accommodation_cost', sa.Float(), nullable=True),
    sa.Column('trip_dining_cost', sa.Float(), nullable=True),
    sa.Column('trip_total_cost', sa.Float(), nullable=True),
    sa.Column('our_response', sa.Text(), nullable=True),
    sa.Column('our_overall_rating', sa.Integer(), nullable=True),
    sa.Column('our_route_rationality_rating', sa.Integer(), nullable=True),
    sa.Column('our_representativeness_rating', sa.Integer(), nullable=True),
    sa.Column('our_currency_unit', sa.String(length=10), nullable=True),
    sa.Column('our_transportation_cost', sa.Float(), nullable=True),
    sa.Column('our_attractions_cost', sa.Float(), nullable=True),
    sa.Column('our_accommodation_cost', sa.Float(), nullable=True),
    sa.Column('our_dining_cost', sa.Float(), nullable=True),
    sa.Column('our_total_cost', sa.Float(), nullable=True),
    sa.Column('feedback', sa.String(length=2000), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('gpt_level_of_details', sa.Integer(), nullable=True),
    sa.Column('our_level_of_details', sa.Integer(), nullable=True),
    sa.Column('trip_level_of_details', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_estimate')
    # ### end Alembic commands ###
